[project]
name = "rl-task-contacts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.72.0",
    "pandas>=2.0.3",
    "pydantic-settings>=2.8.1",
]
